CREATE SCHEMA IF NOT EXISTS demo;
CREATE TABLE IF NOT EXISTS demo.user (ID SERIAL PRIMARY KEY, FIRST_NAME VARCHAR NULL, LAST_NAME VARCHAR NULL, AGE INTEGER NULL, PASSWORD VARCHAR(255) NULL, SALARY BIGINT NULL, USERNAME VARCHAR(255));
